config/routes.rb
Rails.application.routes.draw do

resources :departments do
  resources :items

post '/items/random_items', 'items#random_items' 

end

post '/departments/random_departments', 'departments#random_departments'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  

  def index
    @departments = Department.all
  end

  def show
    @department = Department.find(params[:id])
  end

  def edit
    @department = Department.find(params[:id])
    render partial: "form"
  end

  def update
    @department = Department.find(params[:id])
    if @department.update(department_params)
    redirect_to departments_path
    else
    render partial: "form"
    end
  end

  def new
    @department = Department.new
    render partial: "form"
  end

  def create
    @department = Department.new(department_params)
    if @department.save
    redirect_to departments_path
    else
    render partial: "form"
    end
  end


  def destroy
    @department = Department.find(params[:id]).destroy
    redirect_to departments_path
  end

  def random_departments
      for @department in 1..5 do
      @department = Department.new
      @department.name = Faker::Commerce.department
      @department.description = Faker::ChuckNorris.fact
      @department.save
      end
      redirect_to departments_path
    end

  private

  def department_params
    params.require(:department).permit(:name, :description)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = @department.items
  end

  def show
  end

  def new
    @item = @department.items.new
    render partial: "form"
  end

  def create
    @item = @department.items.new(item_params)
    if @item.save
      redirect_to department_items_path(@department)
    else
      render partial: "form"
    end
  end

  def edit
    @item = Item.find(params[:id])
    render partial: "form"
  end

  def update
    if @item.update(item_params)
    redirect_to department_items_path(@department)
    else
    render partial: "form"
    end
  end

  def destroy
    @item.destroy
    redirect_to department_items_path(@department)
  end

  def random_items
    for @item in 1..5 do
    @item = @department.items.new
    @item.name = Faker::Commerce.product_name
    @item.description = Faker::ChuckNorris.fact
    @item.price = rand(1..100000)
    @item.save
    end
    redirect_to department_items_path(@department)
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price)
  end

  def set_department
    @department = Department.find(params[:department_id])
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/_form.html.erb
<h1><%= @department.name ? 'Edit' : 'Create'  %> Department</h1>
<%= form_for @department do |department| %>
  <%= department.label :name %>
  <%= department.text_field :name %>
  <%= department.label :description %>
  <%= department.text_area :description %>
  <%= department.submit %>
  <% end %>

app/views/departments/index.html.erb
<h1>Departments</h1>
<% @departments.each do |d| %>
<h4><%= link_to d.name, department_items_path(d) %>
<button><%= button_to 'Show', department_path(d), method: :get %></button>
<button><%= button_to 'Edit', edit_department_path(d), method: :get %></button>
<button><%= button_to 'X', d, method: :delete %></button>
</h4>
</h4>

<% end %>
<%= button_to 'New', new_department_path, method: :get %>
<%= button_to 'Create 5 Exciting Departments', departments_random_departments_path, method: :post %>

app/views/departments/show.html.erb
<h1><%=@department.name%> Department</h1>
<h2><%=@department.description%></h2>
<%= button_to 'Back', departments_path, method: :get %>

app/views/items/_form.html.erb
<h1>Item</h1>
<%= form_for [@department, @item] do |item| %>
  <%= item.label :name %>
  <%= item.text_field :name %>
  <%= item.label :description %>
  <%= item.text_area :description %>
  <%= item.label :price %>
  <%= item.text_field :price %>
  <%= item.submit %>
  <% end %>

app/views/items/index.html.erb
<h1><%= @department.name %> Items</h1>
<h2><%= @department.description %></h2>
<% @items.each do |item| %>
<h2><%= link_to item.name, department_item_path(@department, item) %>
<button><%= button_to 'Edit', edit_department_item_path(@department, item), method: :get %></button>
<button><%= button_to 'X', department_item_path(@department, item), method: :delete %></button>
</h2>
<h5><%= item.description %></h5>
<h5><%= item.price %></h5>
<% end %>
<%= button_to 'New', new_department_item_path(@department, @item), method: :get %>
<%= button_to 'back', departments_path, method: :get %>
<%= button_to 'Create 5 Random Items', department_items_random_items_path(@department), method: :post %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<p><%= @item.description %></p>
<h1><%= @item.price %></h1>
<%= button_to 'Back', department_items_path(@department), method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>